

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for RHACM being ready
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for RHACM
# --------------------------------------------------------------------------------------------------------------------------------------

- name: CHECK -          🕦 Wait for more than >{{ RHACM_NS_MIN_PODS }} pods in namespace open-cluster-management
  shell: |
    NUM_PODS=$(oc get po -n open-cluster-management | wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int > RHACM_NS_MIN_PODS
  retries: 500
  delay: 15




- name: CHECK -          🕦 Wait for open-cluster-management to become ready
  shell: oc get po -n open-cluster-management | grep -v Running |grep -v Completed | grep -c ""
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "1"
  retries: 500
  delay: 15


