#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  CP4MCM 3.2 - Ansible Install Parameters
#
#  CloudPak for MultiCloud Management
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"



# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4MCM AI Manager INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# CP4MCM Namespace for installation
MCM_NAMESPACE: cp4mcm

 # Install Foundation (former MultiCloud Manager (MCM)? If you have RHACM installed set this to true
MCM_CORE_DISABLED: true

# CP4MCM Size of the install (small: PoC/Demo, tall: Production)
MCM_SIZE: starterset # Leave at starterset unless you know what you're doing (starterset, small, medium, large)
# Version of the catalog subscription
SUBSCRIPTION_CHANNEL: 2.3-stable




# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# MODULE INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Infrastructure
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install Terraform & Service Automation Module (CAM) ?
INSTALL_INFRA_CAM: false
# Install VM (ManageIQ) Instance ? 
INSTALL_INFRA_VM: true
# Install VM (ManageIQ) Instance ? 
INSTALL_INFRA_GRC: true
# Install VM (ManageIQ) Instance ? 
INSTALL_INFRA_SERVICE_LIBRARY: false


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Monitoring
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install Monitoring Module (APM) ?
INSTALL_MON_MONITORING: false
# Monitor MCM Hub Cluster (register)?
INSTALL_MON_REG_HUB: false



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Security
# ---------------------------------------------------------------------------------------------------------------------------------------------------"

# Register MCM CIS Controller ?
INSTALL_MCMCIS: false
# Register MCM Mutation Advisor ?
INSTALL_MCMMUT: false
# Register MCM Notary ?
INSTALL_MCMNOT: false
# Image Security Enforcment ?
INSTALL_MCMIMGSEC: false
# Vulnerability Advisor ?
INSTALL_MCMVUL: false



# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Operations
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install SRE Chatops ?
INSTALL_OPS_CHAT: false


# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Technology Preview
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Install Manage Runtimes ?
INSTALL_TP_MNG_RT: false






# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4MCM Storage Class Override
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# Override the Storage Class auto detection (ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
STORAGECLASS_FILE_OVERRIDE: not_configured
#STORAGECLASS_FILE_OVERRIDE: ibmc-file-gold-gid          # ROKS
#STORAGECLASS_FILE_OVERRIDE: rook-cephfs                 # FYRE
#STORAGECLASS_FILE_OVERRIDE: nfs-client                  # TEC
STORAGECLASS_BLOCK_OVERRIDE: not_configured
#STORAGECLASS_BLOCK_OVERRIDE: ibmc-block-gold            # ROKS
#STORAGECLASS_BLOCK_OVERRIDE: rook-cephfs                # FYRE
#STORAGECLASS_BLOCK_OVERRIDE: nfs-client                 # TEC







# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# DEMO INSTALL PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# Create a demo user in the OCP cluster
CREATE_DEMO_USER: true

# Install Demo Applications
INSTALL_DEMO_APPS: true

# Print all credentials at the end of the installation
PRINT_LOGINS: true


# Install Rook-Ceph (Should Rook-Ceph be installed (automatic: install when on IBM Fyre) (enable, automatic, disable))
ROOK_CEPH_INSTALL_MODE: automatic


# Install LDAP Server
INSTALL_LDAP: true
# LDAP Domain
LDAP_DOMAIN: ibm.com
# LDAP Base
LDAP_BASE: dc=ibm,dc=com
# LDAP Admin Password
LDAP_ADMIN_PASSWORD: P4ssw0rd!




# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# DO NOT EDIT BELOW
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************
# *************************************************************************************************************************************************





























































# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# WAIOPS INSTALL PARAMETERS (do not change)
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# Name of the CP4MCM instance
MCM_NAME: cp4mcm
# Create externally accessible Route for Topology
CREATE_TOPO_ROUTE: true
# Create externally accessible Routes  (security risk!)
# Flink
# AI Manager API Route
# Datalayer API
CREATE_EXTERNAL_ROUTES: true

# Install the EvtManager --> AI Manegr Gateway
INSTALL_GATEWAY: true
# Number of Pods to be expected in final CP4MCM Namespace
WAIOPS_NS_MIN_PODS_FINAL: 110
# Number of Pods to be expected in final AI Manager Namespace
CS_NS_MIN_PODS: 35
# Number of Pods to be expected in final RookCeph Namespace
ROOK_NS_MIN_PODS: 38
# Number of Pods to be expected in final RHACM Namespace
RHACM_NS_MIN_PODS: 10


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# OCP LOGIN PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
OCP_LOGIN: false
OCP_URL: not_configured
OCP_TOKEN: not_configured

#Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
OCP_MAJOR_VERSION: automatic





# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# IBM ENTITLED REGISTRY PARAMETERS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
# IBM Entitled Registry
ENTITLED_REGISTRY: cp.icr.io
ENTITLED_REGISTRY_USER: cp
ENTITLED_REGISTRY_KEY: TOKEN




























# ENTITLED_REGISTRY: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com
# ENTITLED_REGISTRY_USER: nikh@ch.ibm.com

# CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211029.0822-d63ba3a42
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211022.0601-4c62759e2  <-- worked
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211017.0002-ec2d009bf   <-- worked
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211014.0401-744608902
#CATALOG_IMAGE: hyc-katamari-cicd-team-docker-local.artifactory.swg-devops.com/katamari/relatedimages/ibm-watson-aiops-catalog:v3.2.0-20211011.1801-7097d5a87 <-- worked
#SUBSCRIPTION_CHANNEL: 3.2-dev

#CATALOG_IMAGE: icr.io/cpopen/aiops-orchestrator-catalog:3.2-latest



