---
# tasks file for aiops
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Ansible Install Playbook V0.1
#
#  CloudPak for MultiCloud Management
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Get Config File
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: COMMON SERVICES -      👓 Load parameters
  include_vars: ../00_config_cp4mcm.yaml


# --------------------------------------------------------------------------------------------------------------------------------------
# --------------------------------------------------------------------------------------------------------------------------------------
# Install GENERAL PREREQUISITES
# --------------------------------------------------------------------------------------------------------------------------------------
# --------------------------------------------------------------------------------------------------------------------------------------

# Create Namespace 
- name: COMMON SERVICES -      🚀 Create CP4MCM namespace {{ MCM_NAMESPACE }}
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ MCM_NAMESPACE }}"
    state: present


# Create IBM Operator Catalog
- name: COMMON SERVICES -           🚀 Install IBM Common Services Catalog
  kubernetes.core.k8s:
    state: present
    src: ./templates/common-services/1_cat-common-services.yaml

# Create IBM Operator Subscription
- name: COMMON SERVICES -           🚀 Install IBM Common Services Subscription
  kubernetes.core.k8s:
    state: present
    src: ./templates/common-services/2_sub-common-services.yaml



- name: COMMON SERVICES -           🕦 Wait for Common Services CRD to be ready
  shell: oc get crd commonservices.operator.ibm.com --no-headers|wc -l| tr -d ' '
  register: kubectl_get_crd
  until: kubectl_get_crd.stdout == "1"
  retries: 500
  delay: 15



# Create IBM Operator Subscription
- name: COMMON SERVICES -           🚀 Install IBM Common Services
  kubernetes.core.k8s:
    state: present
    template: ./templates/common-services/3_instance-common-services.j2





