#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4MCM 3.2
#
#  CloudPak for MultiCloud Management
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


- hosts: localhost
  #become: true
  vars_files: ../00_config_cp4mcm.yaml

  roles:  
# Placeholder for customization
    - role: 00_pre


# Install Add-Ons while CP4MCM is coming up
    - role: 25_aiops-addons-ldap
      when: INSTALL_LDAP


# Wait for Common Services being completely installed
    - role: 99_aiops-wait-common-services
      


# Post installation tasks
    - role: 40_aiops-post-ldap-register
      when: INSTALL_LDAP












