---
# tasks file for aiops
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Ansible Install Playbook V0.1
#
#  CloudPak for MultiCloud Management
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Get Config File
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************
- name: RHACM -      👓 Load parameters
  include_vars: ../00_config_cp4mcm.yaml


# --------------------------------------------------------------------------------------------------------------------------------------
# --------------------------------------------------------------------------------------------------------------------------------------
# Install GENERAL PREREQUISITES
# --------------------------------------------------------------------------------------------------------------------------------------
# --------------------------------------------------------------------------------------------------------------------------------------

# Create Namespace 
- name: RHACM -      🚀 Create RHACM namespace open-cluster-management
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "open-cluster-management"
    state: present


# Create IBM Operator Subscription
- name: RHACM -           🚀 Install RHACM Subscription
  kubernetes.core.k8s:
    state: present
    src: ./templates/rhacm/1_sub-rhacm.yaml


- name: RHACM -          🕦 Wait for RHACM Operator to become ready
  shell: oc get csv -n open-cluster-management|grep advanced-cluster-management|grep Succeeded| wc -l| tr -d ' '
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|int == 1
  retries: 500
  delay: 15




# Create IBM Operator Subscription
- name: RHACM -           🚀 Install RHACM
  kubernetes.core.k8s:
    state: present
    template: ./templates/rhacm/2_rhacm-install.yaml





